name: Compile Python to Executable

on:
  release:
    types:
      - published

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build executable for Linux
        run: pyinstaller --onefile main.py

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build executable for Windows
        run: pyinstaller --onefile --windowed main.py

  build-macos-latest:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build executable for macOS
        run: pyinstaller --onefile main.py

  build-macos-13:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build executable for macOS 13
        run: pyinstaller --onefile main.py
